# appveyor.yml
---
image:
  #- macOS
  - Ubuntu
  #- Visual Studio 2019
  
environment:
  matrix:
    # - TOXENV: py27  # https://devguide.python.org/devcycle/#end-of-life-branches
    #- PYTHON: 2.7
    # - TOXENV: py35
    #- PYTHON: 3.5
    #- TOXENV: py36    # https://devguide.python.org/#status-of-python-branches
    - PYTHON: 3.6
    #- TOXENV: py37
    - PYTHON: 3.7
    #- TOXENV: py38
    - PYTHON: 3.8
    #- TOXENV: py39
    - PYTHON: 3.9
    #- TOXENV: py310
    - PYTHON: 3.10

stack: python $PYTHON
build: false

install:
  - pip --version || true
  - py --list || true
  - py -VV || true
  - pip install --upgrade pip
  - pip install tox

test_script:
  - tox py
