# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2022

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma
    TOXENV: py313
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
    TOXENV: py313
  # - TOXENV: py27  # end-of-life branches
  # - TOXENV: py35
  # - TOXENV: py36
  # - TOXENV: py37
  # - TOXENV: py38
  - TOXENV: py39    # https://devguide.python.org/versions
  # - TOXENV: py310
  - TOXENV: py311
  # - TOXENV: py312
  - TOXENV: py313
  - PY_PYTHON: 3.13
  - PY_PYTHON: 3.13-32

build: false

install:
  - py --list || true
  - py -VV || true
  - python3 -VV || python -VV  # python3 on macOS and Ubuntu but python or py on Windows
  - python -VV || true
  - py -m pip install --upgrade pip
  - py -m pip install tox

test_script:
  - py -m tox
