# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Ubuntu
  - Ubuntu2204
  - Visual Studio 2022
  - macOS
  - macos-sonoma

environment:
  matrix:
  #- TOXENV: py36
  #- TOXENV: py37
  #- TOXENV: py38
  - TOXENV: py39
  #- TOXENV: py310
  #- TOXENV: py311
  #- TOXENV: py312
  - TOXENV: py313

build: off

install:
  - node --version
  - npm --version
  - python3 --version || true
  - python --version || true
  - py --list || true
  - py -VV || true
  - pip install tox

test_script:
  - python -m tox
