# appveyor.yml
---
image:
  - macOS
  - Ubuntu
  - Visual Studio 2019
  
environment:
  matrix:
  # - TOXENV: py27  # https://devguide.python.org/devcycle/#end-of-life-branches
  # - TOXENV: py35
  #- TOXENV: py36    # https://devguide.python.org/#status-of-python-branches
  #- TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39    # Not yet present in Appveyor Windows image
  - TOXENV: py310   # Not yet present in Appveyor Windows image

stack: python $PYTHON

build: false

install:
  - python -m pip install --upgrade pip
  - python -m pip install tox

test_script:
  - python -c "import sys ; print(sys.version_info):
  #- python -m tox
  
