# appveyor.yml - https://www.appveyor.com/docs/lang/python
# https://www.appveyor.com/docs/linux-images-software/#python
# https://www.appveyor.com/docs/macos-images-software/#python
# https://www.appveyor.com/docs/windows-images-software/#python
---
image:
  - Visual Studio 2022

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma
    TOXENV: py312
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
    TOXENV: py313
  # - TOXENV: py27  # end-of-life branches
  # - TOXENV: py35
  # - TOXENV: py36
  # - TOXENV: py37
  # - TOXENV: py38
  - TOXENV: py39    # https://devguide.python.org/versions
  # - TOXENV: py310
  # - TOXENV: py311
  # - TOXENV: py312
  - TOXENV: py313
  - PY_PYTHON: 3.13  # %PY_PYTHON% sets py's version on Windows but it does not affect python
  - PY_PYTHON: 3.13-32

build: false

install:
  - py --list || which -a python3  # py is Windows-only in AppVeyor
  - py -VV || true  # py is Windows-only in AppVeyor
  - python -VV || true  # python is Windows-only in AppVeyor
  - python3 -VV || python -VV  # python3 on macOS and Ubuntu but python or py on Windows
  # python3 defaults to 3.9.6 on macos-sonoma and 3.10.12 on Ubuntu2204
  # python3 maximum to 3.12.1 on macos-sonoma and 3.13.0 on Ubuntu2204
  # py or python defaults to 3.12.8 and maximum is 3.13.1 on Visual Studio 2022
  - py -m pip install --upgrade pip || python3 -m pip install --upgrade pip 
  - py -m pip install tox || python3 -m pip install tox

test_script:
  - py -m tox || python3 -m tox
