# appveyor.yml
---
image:
  #- macOS
  #- Ubuntu
  - Visual Studio 2019
  
environment:
  matrix:
    # - TOXENV: py27  # https://devguide.python.org/devcycle/#end-of-life-branches
    # - TOXENV: py35
    - TOXENV: py36    # https://devguide.python.org/#status-of-python-branches
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310
   allow_failures:
    - TOXENV: py310

build: false

install:
  - py --list
  - py -VV
  - py -m pip install --upgrade pip
  - py -m pip install tox

test_script:
  - py -m tox
