# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2022

environment:
  matrix:
  # - TOXENV: py27  # end-of-life branches
  # - TOXENV: py35
  # - TOXENV: py36
  # - TOXENV: py37
  - TOXENV: py38    # https://devguide.python.org/versions
  - TOXENV: py39
  - TOXENV: py310
  - TOXENV: py311
  # - TOXENV: py312  # Not yet
  - PY_PYTHON: 3.11
  - PY_PYTHON: 3.11-32

build: false

install:
  - py --list
  - py -VV
  - py -m pip install --upgrade pip
  - py -m pip install tox

test_script:
  - py -m tox
